// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: characters.sql

package database

import (
	"context"
)

const viewCharacter = `-- name: ViewCharacter :one
SELECT id, name, user_id, class, race, alignment, level, hit_points_total, hit_points_current, languages, religion, secondary_skills, place_of_origin, gender, age, height, weight, eye_color, hair_color, complexion, xp_current, xp_bonus
FROM characters
WHERE id = $1
`

func (q *Queries) ViewCharacter(ctx context.Context, id int32) (Character, error) {
	row := q.db.QueryRowContext(ctx, viewCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Class,
		&i.Race,
		&i.Alignment,
		&i.Level,
		&i.HitPointsTotal,
		&i.HitPointsCurrent,
		&i.Languages,
		&i.Religion,
		&i.SecondarySkills,
		&i.PlaceOfOrigin,
		&i.Gender,
		&i.Age,
		&i.Height,
		&i.Weight,
		&i.EyeColor,
		&i.HairColor,
		&i.Complexion,
		&i.XpCurrent,
		&i.XpBonus,
	)
	return i, err
}
