// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Character struct {
	ID               int32
	Name             string
	UserID           int32
	Class            string
	Race             string
	Alignment        string
	Level            int32
	HitPointsTotal   int32
	HitPointsCurrent int32
	Languages        sql.NullString
	Religion         sql.NullString
	SecondarySkills  sql.NullString
	PlaceOfOrigin    sql.NullString
	Gender           sql.NullString
	Age              sql.NullInt32
	Height           sql.NullString
	Weight           sql.NullInt32
	EyeColor         sql.NullString
	HairColor        sql.NullString
	Complexion       sql.NullString
	XpCurrent        sql.NullInt32
	XpBonus          sql.NullBool
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
