-- +goose Up
INSERT INTO
    weapons (
        name,
        reach,
        cost_gp,
        weight,
        range_short,
        range_medium,
        range_long,
        attacks_per_round,
        damage
    )
VALUES
    ('Axe, Hand', 1, 5, 2, 15, 30, 45, '1/1', '1d6'),
    (
        'Axe, Battle',
        2,
        10,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    (
        'Axe, Great',
        4,
        20,
        10,
        NULL,
        NULL,
        NULL,
        NULL,
        '2d6'
    ),
    ('Cæstuses', 0, 1, 1, NULL, NULL, NULL, NULL, '+1'),
    (
        'Chain Whip',
        4,
        10,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    ('Club, Light', 1, 1, 2, 10, 20, 30, '1/1', '1d4'),
    (
        'Club, War',
        2,
        3,
        4,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6 (1d8)'
    ),
    ('Dagger', 1, 4, 1, 10, 20, 30, '3/2', '1d4'),
    (
        'Dagger, Silver',
        1,
        25,
        1,
        10,
        20,
        30,
        '3/2',
        '1d4'
    ),
    (
        'Falcata',
        1,
        10,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    (
        'Flail, Horseman''s',
        1,
        5,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    (
        'Flail, Footman''s',
        3,
        10,
        10,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d10'
    ),
    (
        'Halberd',
        4,
        15,
        8,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d10'
    ),
    (
        'Hammer, Horseman''s',
        1,
        5,
        3,
        10,
        20,
        30,
        '1/1',
        '1d6'
    ),
    (
        'Hammer, War',
        2,
        10,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    (
        'Hammer, Great',
        4,
        20,
        10,
        NULL,
        NULL,
        NULL,
        NULL,
        '2d6'
    ),
    (
        'Javelin',
        2,
        3,
        3,
        20,
        40,
        80,
        '1/1',
        '1d4 (1d6)'
    ),
    ('Lance', 5, 15, 8, NULL, NULL, NULL, NULL, '1d8'),
    (
        'Mace, Horseman''s',
        1,
        4,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    (
        'Mace, Footman''s',
        2,
        10,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    (
        'Mace, Great',
        4,
        20,
        10,
        NULL,
        NULL,
        NULL,
        NULL,
        '2d6'
    ),
    (
        'Morning Star',
        2,
        15,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    (
        'Pick, Horseman''s',
        1,
        5,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    (
        'Pick, War',
        2,
        15,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    ('Pike', 6, 7, 12, NULL, NULL, NULL, NULL, '1d8'),
    (
        'Quarterstaff',
        3,
        5,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    (
        'Scimitar, Short',
        1,
        10,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    (
        'Scimitar, Long',
        2,
        20,
        4,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    (
        'Scimitar, Two-handed',
        4,
        40,
        6,
        NULL,
        NULL,
        NULL,
        NULL,
        '3d4'
    ),
    ('Sickle', 1, 3, 2, NULL, NULL, NULL, NULL, '1d4'),
    (
        'Spear, Short',
        3,
        4,
        5,
        15,
        30,
        45,
        '1/1',
        '1d6 (1d8)'
    ),
    (
        'Spear, Long',
        4,
        5,
        7,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6 (1d8)'
    ),
    (
        'Spear, Great',
        5,
        7,
        9,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8'
    ),
    (
        'Spiked Staff',
        3,
        15,
        7,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d10'
    ),
    (
        'Sword, Short',
        1,
        10,
        3,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d6'
    ),
    (
        'Sword, Broad',
        2,
        20,
        4,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    (
        'Sword, Long',
        2,
        20,
        4,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (1d10)'
    ),
    (
        'Sword, Bastard',
        3,
        30,
        5,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d8 (2d6)'
    ),
    (
        'Sword, Two-handed',
        4,
        40,
        6,
        NULL,
        NULL,
        NULL,
        NULL,
        '3d4'
    ),
    ('Tonfa', 1, 2, 1, NULL, NULL, NULL, NULL, '1d4'),
    (
        'Trident, Hand',
        1,
        7,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        '1d4'
    ),
    (
        'Trident, Long',
        4,
        10,
        6,
        10,
        20,
        30,
        '1/1',
        '1d6 (1d8)'
    ),
    ('Whip', 5, 1, 2, NULL, NULL, NULL, NULL, '1d2');

-- +goose Down
DELETE FROM weapons;
