// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: equipment.sql

package db

import (
	"context"
)

const listEquipmentSlots = `-- name: ListEquipmentSlots :many
SELECT
    id,
    name,
    description
FROM
    equipment_slots
ORDER BY
    name
`

func (q *Queries) ListEquipmentSlots(ctx context.Context) ([]EquipmentSlot, error) {
	rows, err := q.db.QueryContext(ctx, listEquipmentSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentSlot
	for rows.Next() {
		var i EquipmentSlot
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
